/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers: never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/404': RouteRecordInfo<
      '/404',
      '/404',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/': RouteRecordInfo<
      '/about/',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/about/site': RouteRecordInfo<
      '/about/site',
      '/about/site',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/archives/': RouteRecordInfo<
      '/archives/',
      '/archives',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/categories/': RouteRecordInfo<
      '/categories/',
      '/categories',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/links/': RouteRecordInfo<
      '/links/',
      '/links',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/page/[page]': RouteRecordInfo<
      '/page/[page]',
      '/page/:page',
      { page: ParamValue<true> },
      { page: ParamValue<false> },
      | never
    >,
    '/posts/': RouteRecordInfo<
      '/posts/',
      '/posts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/《坦克大战》': RouteRecordInfo<
      '/posts/《坦克大战》',
      '/posts/%E3%80%8A%E5%9D%A6%E5%85%8B%E5%A4%A7%E6%88%98%E3%80%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/《巫鬼》': RouteRecordInfo<
      '/posts/《巫鬼》',
      '/posts/%E3%80%8A%E5%B7%AB%E9%AC%BC%E3%80%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/《平台跳跃》': RouteRecordInfo<
      '/posts/《平台跳跃》',
      '/posts/%E3%80%8A%E5%B9%B3%E5%8F%B0%E8%B7%B3%E8%B7%83%E3%80%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/《救赎之路》': RouteRecordInfo<
      '/posts/《救赎之路》',
      '/posts/%E3%80%8A%E6%95%91%E8%B5%8E%E4%B9%8B%E8%B7%AF%E3%80%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/《来封印魔王吧！》': RouteRecordInfo<
      '/posts/《来封印魔王吧！》',
      '/posts/%E3%80%8A%E6%9D%A5%E5%B0%81%E5%8D%B0%E9%AD%94%E7%8E%8B%E5%90%A7%EF%BC%81%E3%80%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/《IsoLand2》': RouteRecordInfo<
      '/posts/《IsoLand2》',
      '/posts/%E3%80%8AIsoLand2%E3%80%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/《Moother》': RouteRecordInfo<
      '/posts/《Moother》',
      '/posts/%E3%80%8AMoother%E3%80%8B',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/创建型设计模式-5种': RouteRecordInfo<
      '/posts/创建型设计模式-5种',
      '/posts/%E5%88%9B%E5%BB%BA%E5%9E%8B%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F-5%E7%A7%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/排序算法——交换排序': RouteRecordInfo<
      '/posts/排序算法——交换排序',
      '/posts/%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E4%BA%A4%E6%8D%A2%E6%8E%92%E5%BA%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/排序算法——归并计数基数桶排序': RouteRecordInfo<
      '/posts/排序算法——归并计数基数桶排序',
      '/posts/%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E5%BD%92%E5%B9%B6%E8%AE%A1%E6%95%B0%E5%9F%BA%E6%95%B0%E6%A1%B6%E6%8E%92%E5%BA%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/排序算法——插入排序': RouteRecordInfo<
      '/posts/排序算法——插入排序',
      '/posts/%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E6%8F%92%E5%85%A5%E6%8E%92%E5%BA%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/排序算法——选择排序': RouteRecordInfo<
      '/posts/排序算法——选择排序',
      '/posts/%E6%8E%92%E5%BA%8F%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E9%80%89%E6%8B%A9%E6%8E%92%E5%BA%8F',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/算法——分治算法': RouteRecordInfo<
      '/posts/算法——分治算法',
      '/posts/%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E5%88%86%E6%B2%BB%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/算法——动态规划算法': RouteRecordInfo<
      '/posts/算法——动态规划算法',
      '/posts/%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E5%8A%A8%E6%80%81%E8%A7%84%E5%88%92%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/算法——回溯算法': RouteRecordInfo<
      '/posts/算法——回溯算法',
      '/posts/%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E5%9B%9E%E6%BA%AF%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/算法——最小生成树算法': RouteRecordInfo<
      '/posts/算法——最小生成树算法',
      '/posts/%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E6%9C%80%E5%B0%8F%E7%94%9F%E6%88%90%E6%A0%91%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/算法——最短路径算法': RouteRecordInfo<
      '/posts/算法——最短路径算法',
      '/posts/%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E6%9C%80%E7%9F%AD%E8%B7%AF%E5%BE%84%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/算法——查找算法': RouteRecordInfo<
      '/posts/算法——查找算法',
      '/posts/%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E6%9F%A5%E6%89%BE%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/算法——贪心算法': RouteRecordInfo<
      '/posts/算法——贪心算法',
      '/posts/%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E8%B4%AA%E5%BF%83%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/算法——递归算法': RouteRecordInfo<
      '/posts/算法——递归算法',
      '/posts/%E7%AE%97%E6%B3%95%E2%80%94%E2%80%94%E9%80%92%E5%BD%92%E7%AE%97%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/结构型设计模式-7种': RouteRecordInfo<
      '/posts/结构型设计模式-7种',
      '/posts/%E7%BB%93%E6%9E%84%E5%9E%8B%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F-7%E7%A7%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/行为型设计模式-11种': RouteRecordInfo<
      '/posts/行为型设计模式-11种',
      '/posts/%E8%A1%8C%E4%B8%BA%E5%9E%8B%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F-11%E7%A7%8D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-05-UGUI源码解析——目录': RouteRecordInfo<
      '/posts/2024-07-05-UGUI源码解析——目录',
      '/posts/2024-07-05-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94%E7%9B%AE%E5%BD%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-15-UGUI源码解析——UIBehaviour': RouteRecordInfo<
      '/posts/2024-07-15-UGUI源码解析——UIBehaviour',
      '/posts/2024-07-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94UIBehaviour',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-16-UGUI源码解析——IndexedSet': RouteRecordInfo<
      '/posts/2024-07-16-UGUI源码解析——IndexedSet',
      '/posts/2024-07-16-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94IndexedSet',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-17-UGUI源码解析——ClipperRegistry': RouteRecordInfo<
      '/posts/2024-07-17-UGUI源码解析——ClipperRegistry',
      '/posts/2024-07-17-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94ClipperRegistry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-17-UGUI源码解析——IClipper': RouteRecordInfo<
      '/posts/2024-07-17-UGUI源码解析——IClipper',
      '/posts/2024-07-17-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94IClipper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-18-UGUI源码解析——CanvasUpdateRegistry': RouteRecordInfo<
      '/posts/2024-07-18-UGUI源码解析——CanvasUpdateRegistry',
      '/posts/2024-07-18-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94CanvasUpdateRegistry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-18-UGUI源码解析——LayoutRebuilder': RouteRecordInfo<
      '/posts/2024-07-18-UGUI源码解析——LayoutRebuilder',
      '/posts/2024-07-18-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94LayoutRebuilder',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-20-UGUI源码解析——ILayoutController': RouteRecordInfo<
      '/posts/2024-07-20-UGUI源码解析——ILayoutController',
      '/posts/2024-07-20-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94ILayoutController',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-20-UGUI源码解析——ILayoutElement': RouteRecordInfo<
      '/posts/2024-07-20-UGUI源码解析——ILayoutElement',
      '/posts/2024-07-20-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94ILayoutElement',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-20-UGUI源码解析——ILayoutGroup': RouteRecordInfo<
      '/posts/2024-07-20-UGUI源码解析——ILayoutGroup',
      '/posts/2024-07-20-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94ILayoutGroup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-20-UGUI源码解析——ILayoutIgnorer': RouteRecordInfo<
      '/posts/2024-07-20-UGUI源码解析——ILayoutIgnorer',
      '/posts/2024-07-20-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94ILayoutIgnorer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-20-UGUI源码解析——ILayoutSelfController': RouteRecordInfo<
      '/posts/2024-07-20-UGUI源码解析——ILayoutSelfController',
      '/posts/2024-07-20-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94ILayoutSelfController',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-20-UGUI源码解析——LayoutGroup': RouteRecordInfo<
      '/posts/2024-07-20-UGUI源码解析——LayoutGroup',
      '/posts/2024-07-20-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94LayoutGroup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-23-UGUI源码解析——HorizontalOrVerticalLayoutGroup': RouteRecordInfo<
      '/posts/2024-07-23-UGUI源码解析——HorizontalOrVerticalLayoutGroup',
      '/posts/2024-07-23-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94HorizontalOrVerticalLayoutGroup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-29-UGUI源码解析——GridLayoutGroup': RouteRecordInfo<
      '/posts/2024-07-29-UGUI源码解析——GridLayoutGroup',
      '/posts/2024-07-29-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94GridLayoutGroup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-29-UGUI源码解析——HorizontalLayoutGroup': RouteRecordInfo<
      '/posts/2024-07-29-UGUI源码解析——HorizontalLayoutGroup',
      '/posts/2024-07-29-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94HorizontalLayoutGroup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-07-29-UGUI源码解析——VerticalLayoutGroup': RouteRecordInfo<
      '/posts/2024-07-29-UGUI源码解析——VerticalLayoutGroup',
      '/posts/2024-07-29-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94VerticalLayoutGroup',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-08-06-UGUI源码解析——ContentSizeFitter': RouteRecordInfo<
      '/posts/2024-08-06-UGUI源码解析——ContentSizeFitter',
      '/posts/2024-08-06-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94ContentSizeFitter',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-08-07-UGUI源码解析——LayoutElement': RouteRecordInfo<
      '/posts/2024-08-07-UGUI源码解析——LayoutElement',
      '/posts/2024-08-07-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94LayoutElement',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-08-07-UGUI源码解析——LayoutUtility': RouteRecordInfo<
      '/posts/2024-08-07-UGUI源码解析——LayoutUtility',
      '/posts/2024-08-07-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94LayoutUtility',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-08-18-UGUI源码解析——CoroutineTween': RouteRecordInfo<
      '/posts/2024-08-18-UGUI源码解析——CoroutineTween',
      '/posts/2024-08-18-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94CoroutineTween',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-08-18-UGUI源码解析——Graphic': RouteRecordInfo<
      '/posts/2024-08-18-UGUI源码解析——Graphic',
      '/posts/2024-08-18-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94Graphic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-08-18-UGUI源码解析——IMaterialModifier': RouteRecordInfo<
      '/posts/2024-08-18-UGUI源码解析——IMaterialModifier',
      '/posts/2024-08-18-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94IMaterialModifier',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-08-18-UGUI源码解析——SetPropertyUtility': RouteRecordInfo<
      '/posts/2024-08-18-UGUI源码解析——SetPropertyUtility',
      '/posts/2024-08-18-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94SetPropertyUtility',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-08-18-UGUI源码解析——VertexHelper': RouteRecordInfo<
      '/posts/2024-08-18-UGUI源码解析——VertexHelper',
      '/posts/2024-08-18-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94VertexHelper',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——BaseMeshEffect': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——BaseMeshEffect',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94BaseMeshEffect',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——Button': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——Button',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94Button',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——ClipperRegistry': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——ClipperRegistry',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94ClipperRegistry',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——Clipping': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——Clipping',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94Clipping',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——IClippable': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——IClippable',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94IClippable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——Image': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——Image',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94Image',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——IMaskable': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——IMaskable',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94IMaskable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——Mask': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——Mask',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94Mask',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——MaskableGraphic': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——MaskableGraphic',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94MaskableGraphic',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——MaskUtilities': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——MaskUtilities',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94MaskUtilities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——Outline': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——Outline',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94Outline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——RawImage': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——RawImage',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94RawImage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——RectMask2D': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——RectMask2D',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94RectMask2D',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——Shadow': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——Shadow',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94Shadow',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——StencilMaterial': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——StencilMaterial',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94StencilMaterial',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/2024-09-15-UGUI源码解析——Text': RouteRecordInfo<
      '/posts/2024-09-15-UGUI源码解析——Text',
      '/posts/2024-09-15-UGUI%E6%BA%90%E7%A0%81%E8%A7%A3%E6%9E%90%E2%80%94%E2%80%94Text',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/hello-world': RouteRecordInfo<
      '/posts/hello-world',
      '/posts/hello-world',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Shader学习笔记': RouteRecordInfo<
      '/posts/Shader学习笔记',
      '/posts/Shader%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Unity实用小技巧': RouteRecordInfo<
      '/posts/Unity实用小技巧',
      '/posts/Unity%E5%AE%9E%E7%94%A8%E5%B0%8F%E6%8A%80%E5%B7%A7',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Unity常用Attribue用法': RouteRecordInfo<
      '/posts/Unity常用Attribue用法',
      '/posts/Unity%E5%B8%B8%E7%94%A8Attribue%E7%94%A8%E6%B3%95',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/UnityEdior': RouteRecordInfo<
      '/posts/UnityEdior',
      '/posts/UnityEdior',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/posts/Untiy游戏框架QZGameFramework': RouteRecordInfo<
      '/posts/Untiy游戏框架QZGameFramework',
      '/posts/Untiy%E6%B8%B8%E6%88%8F%E6%A1%86%E6%9E%B6QZGameFramework',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tags/': RouteRecordInfo<
      '/tags/',
      '/tags',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'node_modules/.pnpm/valaxy-theme-yun@0.28.0-beta.1_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy@0.28.0-beta.1_@babel_5bf05b72d2600478953b42a1ce303036/node_modules/valaxy/client/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'pages/404.md': {
      routes:
        | '/404'
      views:
        | never
    }
    'pages/about/index.md': {
      routes:
        | '/about/'
      views:
        | never
    }
    'pages/about/site.md': {
      routes:
        | '/about/site'
      views:
        | never
    }
    'pages/archives/index.md': {
      routes:
        | '/archives/'
      views:
        | never
    }
    'pages/categories/index.md': {
      routes:
        | '/categories/'
      views:
        | never
    }
    'pages/links/index.md': {
      routes:
        | '/links/'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.0-beta.1_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/page/[page].vue': {
      routes:
        | '/page/[page]'
      views:
        | never
    }
    'node_modules/.pnpm/valaxy-theme-yun@0.28.0-beta.1_vue@3.5.22_typescript@5.9.3_/node_modules/valaxy-theme-yun/pages/posts/index.vue': {
      routes:
        | '/posts/'
      views:
        | never
    }
    'pages/posts/《坦克大战》.md': {
      routes:
        | '/posts/《坦克大战》'
      views:
        | never
    }
    'pages/posts/《巫鬼》.md': {
      routes:
        | '/posts/《巫鬼》'
      views:
        | never
    }
    'pages/posts/《平台跳跃》.md': {
      routes:
        | '/posts/《平台跳跃》'
      views:
        | never
    }
    'pages/posts/《救赎之路》.md': {
      routes:
        | '/posts/《救赎之路》'
      views:
        | never
    }
    'pages/posts/《来封印魔王吧！》.md': {
      routes:
        | '/posts/《来封印魔王吧！》'
      views:
        | never
    }
    'pages/posts/《IsoLand2》.md': {
      routes:
        | '/posts/《IsoLand2》'
      views:
        | never
    }
    'pages/posts/《Moother》.md': {
      routes:
        | '/posts/《Moother》'
      views:
        | never
    }
    'pages/posts/创建型设计模式-5种.md': {
      routes:
        | '/posts/创建型设计模式-5种'
      views:
        | never
    }
    'pages/posts/排序算法——交换排序.md': {
      routes:
        | '/posts/排序算法——交换排序'
      views:
        | never
    }
    'pages/posts/排序算法——归并计数基数桶排序.md': {
      routes:
        | '/posts/排序算法——归并计数基数桶排序'
      views:
        | never
    }
    'pages/posts/排序算法——插入排序.md': {
      routes:
        | '/posts/排序算法——插入排序'
      views:
        | never
    }
    'pages/posts/排序算法——选择排序.md': {
      routes:
        | '/posts/排序算法——选择排序'
      views:
        | never
    }
    'pages/posts/算法——分治算法.md': {
      routes:
        | '/posts/算法——分治算法'
      views:
        | never
    }
    'pages/posts/算法——动态规划算法.md': {
      routes:
        | '/posts/算法——动态规划算法'
      views:
        | never
    }
    'pages/posts/算法——回溯算法.md': {
      routes:
        | '/posts/算法——回溯算法'
      views:
        | never
    }
    'pages/posts/算法——最小生成树算法.md': {
      routes:
        | '/posts/算法——最小生成树算法'
      views:
        | never
    }
    'pages/posts/算法——最短路径算法.md': {
      routes:
        | '/posts/算法——最短路径算法'
      views:
        | never
    }
    'pages/posts/算法——查找算法.md': {
      routes:
        | '/posts/算法——查找算法'
      views:
        | never
    }
    'pages/posts/算法——贪心算法.md': {
      routes:
        | '/posts/算法——贪心算法'
      views:
        | never
    }
    'pages/posts/算法——递归算法.md': {
      routes:
        | '/posts/算法——递归算法'
      views:
        | never
    }
    'pages/posts/结构型设计模式-7种.md': {
      routes:
        | '/posts/结构型设计模式-7种'
      views:
        | never
    }
    'pages/posts/行为型设计模式-11种.md': {
      routes:
        | '/posts/行为型设计模式-11种'
      views:
        | never
    }
    'pages/posts/2024-07-05-UGUI源码解析——目录.md': {
      routes:
        | '/posts/2024-07-05-UGUI源码解析——目录'
      views:
        | never
    }
    'pages/posts/2024-07-15-UGUI源码解析——UIBehaviour.md': {
      routes:
        | '/posts/2024-07-15-UGUI源码解析——UIBehaviour'
      views:
        | never
    }
    'pages/posts/2024-07-16-UGUI源码解析——IndexedSet.md': {
      routes:
        | '/posts/2024-07-16-UGUI源码解析——IndexedSet'
      views:
        | never
    }
    'pages/posts/2024-07-17-UGUI源码解析——ClipperRegistry.md': {
      routes:
        | '/posts/2024-07-17-UGUI源码解析——ClipperRegistry'
      views:
        | never
    }
    'pages/posts/2024-07-17-UGUI源码解析——IClipper.md': {
      routes:
        | '/posts/2024-07-17-UGUI源码解析——IClipper'
      views:
        | never
    }
    'pages/posts/2024-07-18-UGUI源码解析——CanvasUpdateRegistry.md': {
      routes:
        | '/posts/2024-07-18-UGUI源码解析——CanvasUpdateRegistry'
      views:
        | never
    }
    'pages/posts/2024-07-18-UGUI源码解析——LayoutRebuilder.md': {
      routes:
        | '/posts/2024-07-18-UGUI源码解析——LayoutRebuilder'
      views:
        | never
    }
    'pages/posts/2024-07-20-UGUI源码解析——ILayoutController.md': {
      routes:
        | '/posts/2024-07-20-UGUI源码解析——ILayoutController'
      views:
        | never
    }
    'pages/posts/2024-07-20-UGUI源码解析——ILayoutElement.md': {
      routes:
        | '/posts/2024-07-20-UGUI源码解析——ILayoutElement'
      views:
        | never
    }
    'pages/posts/2024-07-20-UGUI源码解析——ILayoutGroup.md': {
      routes:
        | '/posts/2024-07-20-UGUI源码解析——ILayoutGroup'
      views:
        | never
    }
    'pages/posts/2024-07-20-UGUI源码解析——ILayoutIgnorer.md': {
      routes:
        | '/posts/2024-07-20-UGUI源码解析——ILayoutIgnorer'
      views:
        | never
    }
    'pages/posts/2024-07-20-UGUI源码解析——ILayoutSelfController.md': {
      routes:
        | '/posts/2024-07-20-UGUI源码解析——ILayoutSelfController'
      views:
        | never
    }
    'pages/posts/2024-07-20-UGUI源码解析——LayoutGroup.md': {
      routes:
        | '/posts/2024-07-20-UGUI源码解析——LayoutGroup'
      views:
        | never
    }
    'pages/posts/2024-07-23-UGUI源码解析——HorizontalOrVerticalLayoutGroup.md': {
      routes:
        | '/posts/2024-07-23-UGUI源码解析——HorizontalOrVerticalLayoutGroup'
      views:
        | never
    }
    'pages/posts/2024-07-29-UGUI源码解析——GridLayoutGroup.md': {
      routes:
        | '/posts/2024-07-29-UGUI源码解析——GridLayoutGroup'
      views:
        | never
    }
    'pages/posts/2024-07-29-UGUI源码解析——HorizontalLayoutGroup.md': {
      routes:
        | '/posts/2024-07-29-UGUI源码解析——HorizontalLayoutGroup'
      views:
        | never
    }
    'pages/posts/2024-07-29-UGUI源码解析——VerticalLayoutGroup.md': {
      routes:
        | '/posts/2024-07-29-UGUI源码解析——VerticalLayoutGroup'
      views:
        | never
    }
    'pages/posts/2024-08-06-UGUI源码解析——ContentSizeFitter.md': {
      routes:
        | '/posts/2024-08-06-UGUI源码解析——ContentSizeFitter'
      views:
        | never
    }
    'pages/posts/2024-08-07-UGUI源码解析——LayoutElement.md': {
      routes:
        | '/posts/2024-08-07-UGUI源码解析——LayoutElement'
      views:
        | never
    }
    'pages/posts/2024-08-07-UGUI源码解析——LayoutUtility.md': {
      routes:
        | '/posts/2024-08-07-UGUI源码解析——LayoutUtility'
      views:
        | never
    }
    'pages/posts/2024-08-18-UGUI源码解析——CoroutineTween.md': {
      routes:
        | '/posts/2024-08-18-UGUI源码解析——CoroutineTween'
      views:
        | never
    }
    'pages/posts/2024-08-18-UGUI源码解析——Graphic.md': {
      routes:
        | '/posts/2024-08-18-UGUI源码解析——Graphic'
      views:
        | never
    }
    'pages/posts/2024-08-18-UGUI源码解析——IMaterialModifier.md': {
      routes:
        | '/posts/2024-08-18-UGUI源码解析——IMaterialModifier'
      views:
        | never
    }
    'pages/posts/2024-08-18-UGUI源码解析——SetPropertyUtility.md': {
      routes:
        | '/posts/2024-08-18-UGUI源码解析——SetPropertyUtility'
      views:
        | never
    }
    'pages/posts/2024-08-18-UGUI源码解析——VertexHelper.md': {
      routes:
        | '/posts/2024-08-18-UGUI源码解析——VertexHelper'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——BaseMeshEffect.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——BaseMeshEffect'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——Button.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——Button'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——ClipperRegistry.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——ClipperRegistry'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——Clipping.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——Clipping'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——IClippable.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——IClippable'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——Image.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——Image'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——IMaskable.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——IMaskable'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——Mask.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——Mask'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——MaskableGraphic.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——MaskableGraphic'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——MaskUtilities.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——MaskUtilities'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——Outline.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——Outline'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——RawImage.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——RawImage'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——RectMask2D.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——RectMask2D'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——Shadow.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——Shadow'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——StencilMaterial.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——StencilMaterial'
      views:
        | never
    }
    'pages/posts/2024-09-15-UGUI源码解析——Text.md': {
      routes:
        | '/posts/2024-09-15-UGUI源码解析——Text'
      views:
        | never
    }
    'pages/posts/hello-world.md': {
      routes:
        | '/posts/hello-world'
      views:
        | never
    }
    'pages/posts/Shader学习笔记.md': {
      routes:
        | '/posts/Shader学习笔记'
      views:
        | never
    }
    'pages/posts/Unity实用小技巧.md': {
      routes:
        | '/posts/Unity实用小技巧'
      views:
        | never
    }
    'pages/posts/Unity常用Attribue用法.md': {
      routes:
        | '/posts/Unity常用Attribue用法'
      views:
        | never
    }
    'pages/posts/UnityEdior.md': {
      routes:
        | '/posts/UnityEdior'
      views:
        | never
    }
    'pages/posts/Untiy游戏框架QZGameFramework.md': {
      routes:
        | '/posts/Untiy游戏框架QZGameFramework'
      views:
        | never
    }
    'pages/projects/index.md': {
      routes:
        | '/projects/'
      views:
        | never
    }
    'pages/tags/index.md': {
      routes:
        | '/tags/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
